clientesservice:
    consultaclientes:
        wsdlLocation: http://192.168.21.161:8081/mockAnalisisRiesgos/services/mockAnalisisRiesgos?wsdl

spring:
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.Oracle10gDialect"
  datasource:
    url: "jdbc:oracle:thin:@192.168.21.161:1523:xe"
    username: "adminriesgos"
    password: "Optipwd1"
    driver-class-name: "oracle.jdbc.OracleDriver"
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.21.191:30761/
