
estadosfinancieros:
  nombrepropiedad1:
    value: hola
  nombrepropiedad2:
    value: como estas
  nombrepropiedad3:
    value: bienvenido propiedad desde git

estadosfinancierosservice:
    consultaestadosfinancieros:
        wsdlLocation: http://192.168.21.100:8081/mockAnalisisRiesgos/services/mockAnalisisRiesgos?wsdl

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://localhost:3306/test_db"
    username: "root"
    password: "Admin123"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.21.100:8761/eureka
      
