##################################################################
#
# Service: notasservice
# Environment: Production (PRO)
# 
##################################################################

repository:
  ormFile: orm.xml
server:
  port: 8007
  
spring:
  application:
    name: authorizationservice
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.Oracle10gDialect"
  datasource:
    url: "jdbc:oracle:thin:@192.168.21.192:1523:prodriesg"
    username: "sirProd"
    password: "sirProd1"
    driver-class-name: "oracle.jdbc.OracleDriver"
    

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.21.192:8761/eureka

ldap:
  enabled: true
  urls: ldap://ldap.forumsys.com:389/
  base:
    dn: dc=example,dc=com
  username: cn=read-only-admin,dc=example,dc=com
  password: password
  user:
    dn:
      pattern: uid={0}
signing:
  key: 345345fsdgsf5345

  
