##################################################################
#
# Service: authorizationserver
# Environment: Development (DEV)
#
##################################################################
  
repository:
  ormFile: orm.xml
server:
  port: 8901

spring:
  application:
    name: authorizationserver
    
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.Oracle10gDialect"
  datasource:
    url: "jdbc:oracle:thin:@192.168.21.192:1523:prodriesg"
    username: "sirProd"
    password: "sirProd1"
    driver-class-name: "oracle.jdbc.OracleDriver"


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
security:
  oauth2:
    resource:
      filter-order: 3

ldap:
  url: "ldap://ldap.forumsys.com:389/dc=example,dc=com"
  ldif: "classpath:test.ldif"
  user-search-base:
  user-dn-patterns: "uid={0}"
  group-search-base:
  group-search-filter: "(uniqueMember={0})"
