##################################################################
#
# Service: estadosfinancieros
# Enviroment: Development (DEV)
# 
##################################################################
server:
  port: 8001

estadosfinancierosservice:
    consultaestadosfinancieros:
        wsdlLocation: http://192.168.21.192:8081/mockAnalisisRiesgos/services/mockAnalisisRiesgos?wsdl

spring:
  application:
    name: estadosfinancierosservice
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.Oracle10gDialect"
  datasource:
    url: "jdbc:oracle:thin:@192.168.21.192:1523:devRiesgos"
    username: "sirDev"
    password: "sirDev1"
    driver-class-name: "oracle.jdbc.OracleDriver"
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
