##################################################################
#
# Service: rolesservice
# Environment: Development (DEV)
# 
##################################################################

repository:
    ormFile: orm.xml
    
server:
    port: 8007

spring:
    application:
        name: rolesservice
    jpa:
        show-sql: "true"
        properties:
            hibernate:
                dialect: "org.hibernate.dialect.Oracle10gDialect"
                format_sql: "true"
    datasource:
        url: "jdbc:oracle:thin:@192.168.21.192:1523:devRiesgos"
        username: "sirDev"
        password: "sirDev1"
        driver-class-name: "oracle.jdbc.OracleDriver"
        
security:
    ignored: /**
    oauth2:
        resource:
            userInfoUri: http://localhost:8901/users/user            

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
      
rolesservice:
    security:
        enabled: false
