##################################################################
#
# Service: ratiosflujococ
# Environment: Production (PRO)
# 
##################################################################
ratiosflujococ:
  repository:
    ormFile: orm.xml

spring:
  application:
    name: ratiosflujococservice
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.Oracle10gDialect"
        format_sql: "true"

  datasource:
    url: "jdbc:oracle:thin:@192.168.21.100:1523:sirProduccion"
    username: "c##produccion"
    password: "testing12"
    driver-class-name: "oracle.jdbc.OracleDriver"
    max-active: 1
    tomcat:
      initial-size: 1
    initialize: true


server:
  port: 8005

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.21.100:8761/eureka
