##################################################################
#
# Service: reportesfinancieros
# Environment: Development (DEV)
#
##################################################################

repository:
  ormFile: orm.xml
server:
  port: 8003

spring:
  jpa:
    show-sql: "false"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.Oracle10gDialect"
  datasource:
    url: "jdbc:oracle:thin:@192.168.21.192:1523:devRiesgos"
    username: "sirDev"
    password: "sirDev1"
    driver-class-name: "oracle.jdbc.OracleDriver"
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/users/user        

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

reportesfinancierosservice:
  security:
    enabled: false
