##################################################################
#
# Service: reportesfinancieros
# Environment: Development (DEV)
#
##################################################################
  
repository:
    ormFile: orm.xml
server:
    port: 8003

spring:
    jpa:
        show-sql: "true"
        properties:
            hibernate:
                dialect: "org.hibernate.dialect.Oracle10gDialect"
    datasource:
        url: "jdbc:oracle:thin:@192.168.21.192:1523:prodriesg"
        username: "sirProd"
        password: "sirProd1"
        driver-class-name: "oracle.jdbc.OracleDriver"

security:
    ignored: /**
    oauth2:
        resource:
            userInfoUri: http://localhost:8901/users/user    
       
reportesfinancierosservice:
    security:
        enabled: false

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
      

