##################################################################
#
# Service: notasservice
# Environment: Development (DEV)
# 
##################################################################

repository:
    ormFile: orm.xml
server:
  port: 8006

spring:
  application:
    name: notasservice
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.Oracle10gDialect"
        format_sql: "true"
  datasource:
    url: "jdbc:oracle:thin:@192.168.21.192:1523:devRiesgos"
    username: "sirDev"
    password: "sirDev1"
    driver-class-name: "oracle.jdbc.OracleDriver"
    

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
