##################################################################
#
# Service: notasservice
# Environment: Production (PRO)
# 
##################################################################

notasservice:
  repository:
    ormFile: orm.xml
server:
  port: 8006
  
spring:
  application:
    name: notasservice
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.Oracle10gDialect"
  datasource:
    url: "jdbc:oracle:thin:@192.168.21.192:1523:prodriesg"
    username: "sirProd"
    password: "sirProd1"
    driver-class-name: "oracle.jdbc.OracleDriver"
    

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.21.192:8761/eureka
